package com.epam.courses2;

import java.io.File;
import java.io.IOException;
import java.io.BufferedWriter;
import java.io.FileWriter;

public class Hello2{
	
	private static String helloClass = "\npackage com.epam.courses3;\npublic class Hello {\npublic static void main(String[] args){\nSystem.out.println(\"Good night fella. This class is generated by Hello2\");\n}\n}";
	
	public static void main(String[] args) throws IOException {
		
		BufferedWriter writer = new BufferedWriter(new FileWriter("Hello.java"));
		writer.write(helloClass);
		writer.close();
		
		
	}
	
	
	
}